### ISSUE TITLE
Ignore specific routes

### ISSUE THREAD

**Issue by jclusso** [davishmcclurg/webpacker-routes#32]
When we switch between environments we constantly get regenerated routes that are environment specific. For example we get routes like /rails/mailers which show up if we run the rails app in different environments. Is there anyway to set certain routes to just be ignored? If not, is this something you'd be open to adding? This could maybe be done with a file like `.webpacker-routes-ignore` that functions similar to how `.gitignore` works.

**Comment by davishmcclurg** [comment]
Are the extra routes causing issues? The generated routes file itself shouldn't be checked into git.

**Comment by jclusso** [comment]
So app/webpacker/routes/index.js can be added to the gitignore?

**Comment by davishmcclurg** [comment]
Yeah, that should've been handled for you when you ran `bundle exec rails webpacker:install:routes`: https://github.com/davishmcclurg/webpacker-routes/blob/8ce3bfb40601c0c32d66789e4e534b00ac82d5a3/lib/install/template.rb#L2

Was `app/webpacker/routes/.gitignore` generated for you?

**Comment by jclusso** [comment]
@davishmcclurg it doesn't exist on this project but on another one it does. Maybe I never ran the install when we set it up...? Anyway I guess this can be closed. Thanks.
