### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by seuros** [davishmcclurg/webpacker-routes#71]
Any plan to release a version to rubygems ?  Thanks

**Comment by davishmcclurg** [comment]
I just released 0.1.5 with the most recent changes.
I had to add rails and sqlite back as dev dependencies to get tests working again: https://github.com/davishmcclurg/webpacker-routes/commit/845fac86588dbef5e72a7f9f624e72561d64ae74
They were removed in your PR here: https://github.com/davishmcclurg/webpacker-routes/pull/55
Let me know if that causes problems.

**Comment by seuros** [comment]
Thanks. Yes the dummy app need the full stack, however the gem  needs only the engine part.

**Comment by davishmcclurg** [comment]
Sounds good—thanks @seuros!
